name: Crystal CI

on: 
  push:
    branches: 
      - master
      - release/*
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install -v
    - name: Run tests
      run: crystal spec
